project:
  type: website
  resources:
    - CNAME
    - styles.css

website:
  title: "Alex Semenoff"
  site-url: "https://semenoffalex.me"
  description: "(Social | Network | Data) Scientist"
  google-analytics: "G-B88FFFG4ZP"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    minimal: true
